SELECT
    I.NAME,
    I.DATETIME
FROM
    ANIMAL_INS I
LEFT JOIN
    ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE
    O.ANIMAL_ID IS NULL
ORDER BY
    I.DATETIME
LIMIT 3;
    
SELECT
    I.NAME,
    I.DATETIME
FROM
    ANIMAL_INS I
WHERE
    I.ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
ORDER BY
    I.DATETIME
LIMIT 3;